name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 */12 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: "Activity"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_limit: 5
          plugin_activity_days: 0
      - name: "Wakatime"
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          user: revi
          plugin_wakatime_repositories_visibility: public

