name: Todoist Readme Update

on:
  workflow_dispatch:
  schedule:
    # Runs at 13:55 UTC (22:55 KST) every day
    - cron: '55 13 * * *'

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: true